language: go
go:
- '1.11'
- 'tip'
matrix:
  fast_finish: true
  allow_failures:
  - go: 'tip'
env:
- GO111MODULE=on
install: go mod download
script: make ci
after_success: bash <(curl -s https://codecov.io/bash)
